port 26479
dir "/private/tmp"
sentinel monitor mymaster 127.0.0.1 6479 2
sentinel down-after-milliseconds mymaster 5000

sentinel failover-timeout mymaster 5000
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
